version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  # polling_api:
  #   build: .
  #   container_name: polling_api
  #   depends_on:
  #     - sqlserver
  #   environment:
  #     ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PollingDB;User Id=sa;Password=YourStrong!Passw0rd;"
  #   ports:
  #     - "5000:5000"
  #     - "5001:5001"
  #   restart: always

volumes:
  sql_data:
